h265nal: fix SPS PicWidthInCtbsY/PicHeightInCtbsY calculatiuon
When using `Ceil()`, we need to make sure the division is float.

Tested:

Build and re-run 1 fuzzer case:

```
$ ./fuzz/h265_rtp_ap_parser_fuzzer ../fuzz/corpus/h265_rtp_ap_parser_fuzzer/oom-e13c9b1aab8aff39a2e76451deb0b6ca855b4ecc
INFO: Seed: 3692649319
INFO: Loaded 1 modules   (368 inline 8-bit counters): 368 [0x5f7080, 0x5f71f0),
INFO: Loaded 1 PC tables (368 PCs): 368 [0x5bc648,0x5bdd48),
./fuzz/h265_rtp_ap_parser_fuzzer: Running 1 inputs 1 time(s) each.
Running: ../fuzz/corpus/h265_rtp_ap_parser_fuzzer/oom-e13c9b1aab8aff39a2e76451deb0b6ca855b4ecc
error: vps->vps_num_layer_sets_minus1 value too large: 142177
error: unimplemented pps_range_extension() in pps
error: invalid slice_segment_header->num_entry_point_offsets: 471
error: invalid slice_segment_header->num_entry_point_offsets: 8
error: invalid slice_segment_header->num_entry_point_offsets: 191
error: unimplemented scaling_list_data() in pps
error: vps->vps_num_layer_sets_minus1 value too large: 2274850
error: unimplemented scaling_list_data() in pps
error: invalid slice_segment_header->num_entry_point_offsets: 2
error: invalid slice_segment_header->num_entry_point_offsets: 1105985698
error: invalid slice_segment_header->num_entry_point_offsets: 4
Executed ../fuzz/corpus/h265_rtp_ap_parser_fuzzer/oom-e13c9b1aab8aff39a2e76451deb0b6ca855b4ecc in 2 ms
***
*** NOTE: fuzzing was not performed, you have only
***       executed the target code on a fixed set of inputs.
***
```