h265nal: fix issue on slice parser
We need to check that there is a sps_scc_extension before accessing
to it.

Found by fuzzing.

Tested:

Run the previous case:

```
../build/fuzz/h265_bitstream_parser_fuzzer corpus/h265_bitstream_parser_fuzzer/crash-ac2dab573cf0f83e21257ff3808c4f33da58064e
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 2390561950
INFO: Loaded 1 modules   (1634 inline 8-bit counters): 1634 [0x65b9d0, 0x65c032),
INFO: Loaded 1 PC tables (1634 PCs): 1634 [0x60f7a8,0x615dc8),
../build/fuzz/h265_bitstream_parser_fuzzer: Running 1 inputs 1 time(s) each.
Running: corpus/h265_bitstream_parser_fuzzer/crash-ac2dab573cf0f83e21257ff3808c4f33da58064e
error: cannot ParseNalUnitHeader in nal unit
Could not parse a buffer into a NalUnit
error: cannot ParseNalUnitHeader in nal unit
Could not parse a buffer into a NalUnit
error: cannot ParseNalUnitHeader in nal unit
Could not parse a buffer into a NalUnit
error: cannot ParseNalUnitHeader in nal unit
Could not parse a buffer into a NalUnit
error: cannot ParseNalUnitHeader in nal unit
Could not parse a buffer into a NalUnit
error: cannot ParseNalUnitHeader in nal unit
Could not parse a buffer into a NalUnit
error: cannot ParseNalUnitHeader in nal unit
Could not parse a buffer into a NalUnit
error: cannot ParseNalUnitHeader in nal unit
Could not parse a buffer into a NalUnit
error: cannot ParseNalUnitHeader in nal unit
Could not parse a buffer into a NalUnit
error: cannot ParseNalUnitHeader in nal unit
Could not parse a buffer into a NalUnit
error: cannot ParseNalUnitHeader in nal unit
Could not parse a buffer into a NalUnit
error: cannot ParseNalUnitHeader in nal unit
Could not parse a buffer into a NalUnit
error: cannot ParseNalUnitHeader in nal unit
Could not parse a buffer into a NalUnit
error: cannot ParseNalUnitHeader in nal unit
Could not parse a buffer into a NalUnit
Executed corpus/h265_bitstream_parser_fuzzer/crash-ac2dab573cf0f83e21257ff3808c4f33da58064e in 6 ms
***
*** NOTE: fuzzing was not performed, you have only
***       executed the target code on a fixed set of inputs.
***
```