h265nal: add interesting results from 10^6 fuzz pass
```
$ ../build/fuzz/h265_bitstream_parser_fuzzer corpus/h265_bitstream_parser_fuzzer/crash-ac2dab573cf0f83e21257ff3808c4f33da58064e
INFO: Running with entropic power schedule (0xFF, 100).
INFO: Seed: 2239583998
INFO: Loaded 1 modules   (1634 inline 8-bit counters): 1634 [0x65b9d0, 0x65c032),
INFO: Loaded 1 PC tables (1634 PCs): 1634 [0x60f7a8,0x615dc8),
../build/fuzz/h265_bitstream_parser_fuzzer: Running 1 inputs 1 time(s) each.
Running: corpus/h265_bitstream_parser_fuzzer/crash-ac2dab573cf0f83e21257ff3808c4f33da58064e
error: cannot ParseNalUnitHeader in nal unit
Could not parse a buffer into a NalUnit
error: cannot ParseNalUnitHeader in nal unit
Could not parse a buffer into a NalUnit
error: cannot ParseNalUnitHeader in nal unit
Could not parse a buffer into a NalUnit
error: cannot ParseNalUnitHeader in nal unit
Could not parse a buffer into a NalUnit
error: cannot ParseNalUnitHeader in nal unit
Could not parse a buffer into a NalUnit
AddressSanitizer:DEADLYSIGNAL
=================================================================
==1231024==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000030 (pc 0x0000005ceec0 bp 0x7ffcc3ab8dd0 sp 0x7ffcc3ab8870 T0)
==1231024==The signal is caused by a READ memory access.
==1231024==Hint: address points to the zero page.
    #0 0x5ceec0 in h265nal::H265SliceSegmentHeaderParser::ParseSliceSegmentHeader(rtc::BitBuffer*, unsigned int, h265nal::H265BitstreamParserState*) h265nal/src/h265_slice_parser.cc:477:38
    #1 0x5cd384 in h265nal::H265SliceSegmentLayerParser::ParseSliceSegmentLayer(rtc::BitBuffer*, unsigned int, h265nal::H265BitstreamParserState*) h265nal/src/h265_slice_parser.cc:51:7
    #2 0x5b59e4 in h265nal::H265NalUnitPayloadParser::ParseNalUnitPayload(rtc::BitBuffer*, unsigned int, h265nal::H265BitstreamParserState*) h265nal/src/h265_nal_unit_parser.cc:163:11
    #3 0x5b56cc in h265nal::H265NalUnitParser::ParseNalUnit(rtc::BitBuffer*, h265nal::H265BitstreamParserState*, bool) h265nal/src/h265_nal_unit_parser.cc:65:32
    #4 0x5b5518 in h265nal::H265NalUnitParser::ParseNalUnit(unsigned char const*, unsigned long, h265nal::H265BitstreamParserState*, bool) h265nal/src/h265_nal_unit_parser.cc:35:10
    #5 0x5b2ab4 in h265nal::H265BitstreamParser::ParseBitstream(unsigned char const*, unsigned long, h265nal::H265BitstreamParserState*, bool) h265nal/src/h265_bitstream_parser.cc:94:21
    #6 0x5988d7 in LLVMFuzzerTestOneInput h265nal/fuzz/h265_bitstream_parser_fuzzer.cc:22:20
    #7 0x4986b9 in fuzzer::Fuzzer::ExecuteCallback(unsigned char const*, unsigned long) (h265nal/build/fuzz/h265_bitstream_parser_fuzzer+0x4986b9)
    #8 0x47994f in fuzzer::RunOneTest(fuzzer::Fuzzer*, char const*, unsigned long) (h265nal/build/fuzz/h265_bitstream_parser_fuzzer+0x47994f)
    #9 0x4813ae in fuzzer::FuzzerDriver(int*, char***, int (*)(unsigned char const*, unsigned long)) (h265nal/build/fuzz/h265_bitstream_parser_fuzzer+0x4813ae)
    #10 0x470aa6 in main (h265nal/build/fuzz/h265_bitstream_parser_fuzzer+0x470aa6)
    #11 0x7fe01df87b74 in __libc_start_main /usr/src/debug/glibc-2.33-20.fc34.x86_64/csu/../csu/libc-start.c:332:16
    #12 0x470afd in _start (h265nal/build/fuzz/h265_bitstream_parser_fuzzer+0x470afd)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV h265nal/src/h265_slice_parser.cc:477:38 in h265nal::H265SliceSegmentHeaderParser::ParseSliceSegmentHeader(rtc::BitBuffer*, unsigned int, h265nal::H265BitstreamParserState*)
==1231024==ABORTING
```